# Generated by Django 2.1 on 2019-09-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controlador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdControlador', models.CharField(max_length=20)),
                ('Edificio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pantalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdPantalla', models.CharField(max_length=20)),
                ('Edificio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=25)),
                ('User_password', models.CharField(max_length=10)),
                ('User_email', models.CharField(max_length=50)),
            ],
        ),
    ]
