# Generated by Django 2.1 on 2019-09-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pantalla_piso'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlador',
            name='Piso',
            field=models.CharField(choices=[('UNO', 'PB'), ('BAJA', 'P1'), ('DOS', 'P2')], default='UNO', max_length=4),
        ),
    ]
