# Generated by Django 3.0 on 2020-01-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191217_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='IP',
            field=models.CharField(default='192.168.0.0', max_length=16),
        ),
    ]
